Repository modern-agile-team/dongurami-server, pull requests merged in 2021-12, with the labels that each got.

#389 [boards]: 전체공지게시판 생성 관리자만 가능하게 수정
  app/src/apis/boards/board.ctrl.js
  app/src/models/services/Board/Board.js
Labels: 서버, 기능 구현, API

#390 [Letter] 쪽지 API
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#391 [clubBoard] 동아리 별 활동 내역 및 공지 게시판 API
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#392 [schedule] 동아리 일정 API
  app/src/middlewares/club-auth.js
Labels: 서버, 기능 구현, API

#393 [letter] 쪽지 API
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#394 [Letter] 쪽지 API
  app/src/apis/letter/index.js
  app/src/apis/letter/letter.ctrl.js
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#395 [profile]: 프로필 수정 500번 에러 수정
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#397 [applicationForm] 동아리 가입 질문 API
  app/src/apis/application/application.ctrl.js
  app/src/apis/application/index.js
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#396 [Letter] 쪽지 API
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#398 [Search] 검색 API
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: 기능 구현, API, DB

#400 [circle-home] 동아리 홈 API
  app/src/models/services/CircleHome/Home.js
  app/src/models/services/CircleHome/HomeStorage.js
Labels: 서버, 기능 구현, API

#401 [Notification] 일정 알림 수정
  app/src/models/services/Schedule/Schedule.js
Labels: 서버, 기능 구현, API

#403 [Test] 테스트 코드 리팩토링
  app/src/models/services/Review/Review.js
  app/src/tests/admin-option.test.js
  app/src/tests/board-notification.test.js
  app/src/tests/club-notification.test.js
  app/src/tests/review.test.js
Labels: 서버, 기능 구현, API

#405 [Boards]: 게시글 조회수 API
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: 버그, 서버, 기능 구현, API

#407 [boards]: 게시판, 댓글 modify_date 코드 제거
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/CommentStorage.js
Labels: 서버, API, DB

#408 [myPage] 마이페이지 활동내역 스크랩 API
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 서버, 기능 구현, API

#409 검색 modify_date 코드 제거
  app/src/models/services/Board/BoardStorage.js
Labels: DB

#412 [Notification] 전체 공지 게시판에서 글 생성시 모든 회원에게 알람 가도록 기능 추가
  app/src/models/services/Board/Board.js
  app/src/models/services/Student/StudentStorage.js
  app/src/tests/board-notification.test.js
Labels: 서버, 기능 구현, API

#414 [Notification] 게시판 알림 생성 API 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Notification/Notification.js
Labels: 서버, 기능 구현, API

#415 [boards]: 본인이 본인 글 조회수 증가시키지 못하게 수정 그에따른 상태코드 수정
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: 서버, 기능 구현, API

#416 [boards]: 게시글 조회시 조회수 api 때문에 조회되지 않는 오류 수정
  app/src/apis/boards/board.ctrl.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: 버그, 서버, 기능 구현, API

#418 [Naver] 네이버 OAuth API
  app/src/models/services/Student/StudentStorage.js
Labels: API

#419 [Review] GET 요청 시 내림차순으로 데이터 반환하도록 수정
  app/src/models/services/Review/ReviewStorage.js
Labels: 서버, 기능 구현, API

#420 [profile]: 네이버 유저 이메일 변경 못하게 수정
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Student/StudentStorage.js
Labels: 서버, 기능 구현, API

#421 [Notification] 알림 API 수정
  app/src/models/services/Application/Application.js
  app/src/models/services/Notification/Notification.js
  app/src/tests/board-notification.test.js
Labels: 서버, 기능 구현, API

#422 [profile]: 프로필 조회 및 수정시 isNaverUser 에러 수정
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Student/StudentStorage.js
Labels: 버그, 서버, 기능 구현, API

#423 [Letter] 쪽지 API
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#424 [myPage] 마이페이지 작성 글 & 작성 댓글 모아 보기 API
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 서버, 기능 구현, API
