Repository modern-agile-team/dongurami-server, pull requests merged in 2021-08, with the labels that each got.

#7 Add(jisu/login): 테스트 중
  README.md
  app/bin/www.js
Labels: 서버, 기획 및 설계

#9 Add(changhoon/develop) :
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .github/PULL_REQUEST_TEMPLATE.md
  app/package-lock.json
Labels: 기획 및 설계

#12 Add(seokho/mariaDB) : #11
  app/package-lock.json
  app/package.json
  app/src/config/mariadb.js
  app/src/config/test.js
Labels: DB

#13 Add(seokho/mariaDB) : #11
  app/package-lock.json
  app/package.json
  app/src/config/mariadb.js
  app/src/config/test.js
Labels: DB

#15 Add(seokho/setup): 초기설정
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
Labels: 서버, 기획 및 설계

#16 Add(seokho/setup): 초기설정
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
Labels: 서버, 기획 및 설계

#18 nodemon 설정
  app/package-lock.json
  app/package.json
Labels: 기획 및 설계

#19 nodemon 설정
  app/package-lock.json
  app/package.json
Labels: 기획 및 설계

#20 Update(jisu): .prettierrc.json 파일 생성
  app/.eslintrc.json
  app/.prettierrc.json
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/src/config/mariadb.js
Labels: 기획 및 설계

#21 package.json 파일 수정
  app/package.json
Labels: 기획 및 설계

#25 [setup] use strict 사용을 위한 수정
  app/.eslintrc.json
  app/package-lock.json
  app/package.json
Labels: 기획 및 설계
