Repository modern-agile-team/dongurami-server, pull requests merged in 2021-11, with the labels that each got.

#300 [boards]: 홍보게시판 생성, 수정 시 이미지 없을 때 안되게 처리 #270
  app/src/models/services/Board/Board.js
  app/src/models/services/Image/Image.js
Labels: 서버, 기능 구현, API

#301 [boards]: 홍보게시판 생성, 수정 시 이미지 없을 때 안되게 처리
  app/src/models/services/Board/Board.js
  app/src/models/services/Image/Image.js
Labels: 서버, 기능 구현, API

#303 [Boards]: 공지게시판 생성, 수정, 삭제 관리자만 접근 가능하게 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Club/ClubStorage.js
Labels: 서버, 기능 구현, API

#304 [Boards]: 공지게시판 생성, 수정, 삭제 관리자만 접근 가능하게 수정
  app/src/models/services/Board/Board.js
Labels: 서버, 기능 구현, API

#305 [ClubListSearch] 동아리 목록 검색 API
  app/src/apis/search/index.js
  app/src/apis/search/search.ctrl.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Club/Club.js
  app/src/models/services/Club/ClubStorage.js
Labels: 기능 구현, API, DB

#306 [ClubListSearch] 동아리 목록 검색 API
  app/src/apis/search/index.js
  app/src/apis/search/search.ctrl.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Club/Club.js
  app/src/models/services/Club/ClubStorage.js
Labels: 기능 구현, API, DB

#307 [applicationForm] 동아리 가입 답변 API
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#308 [applicationForm] 동아리 가입 답변 API
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#309 [myPage] 마이페이지 활동내역 스크랩 API
  app/src/apis/my-page/my-page.ctrl.js
  app/src/models/services/Image/Image.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 서버, 기능 구현, API

#311 [profile] 프로필 수정시 프로필 이미지 바뀌면 jwt재발급 #127
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#310 [myPage] 마이페이지 활동내역 스크랩 API
  app/src/apis/my-page/my-page.ctrl.js
  app/src/models/services/Image/Image.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 서버, 기능 구현, API

#312 [profile] 프로필 수정시 프로필 이미지 바뀌면 jwt재발급
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#313 [Notification] 알림 API 수정
  app/package-lock.json
  app/src/apis/schedule/index.js
  app/src/apis/schedule/schedule.ctrl.js
  app/src/models/services/AdminOption/AdminOptionStorage.js
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Notification/Notification.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/models/services/Schedule/Schedule.js
Labels: 서버, 기능 구현, API

#314 [Notification] 알림 API 수정
  app/package-lock.json
  app/src/apis/schedule/index.js
  app/src/apis/schedule/schedule.ctrl.js
  app/src/models/services/AdminOption/AdminOptionStorage.js
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Notification/Notification.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/models/services/Schedule/Schedule.js
Labels: 서버, 기능 구현, API

#317 [applicationForm] 동아리 가입 답변 API
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#320 [boards]: 게시판, 댓글, 답글 수정 삭제 버그 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#318 [applicationForm] 동아리 가입 답변 API
  app/src/models/services/Application/Application.js
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#316 [LeaveClub] 동아리 탈퇴 API
  app/src/apis/my-page/index.js
  app/src/apis/my-page/my-page.ctrl.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 기능 구현, API, DB

#323 Boards: 게시글, 댓글, 답글 수정 삭제 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#319 [clubBoard] 동아리 별 활동 내역 및 공지 게시판 API
  app/src/models/services/AdminOption/AdminOptionStorage.js
  app/src/models/services/Board/Board.js
Labels: 서버, 기능 구현, API

#324 [LeaveClub] 동아리 탈퇴 API
  app/src/apis/my-page/index.js
  app/src/apis/my-page/my-page.ctrl.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/MyPage/MyPageStorage.js
Labels: 기능 구현, API, DB

#327 Modify(changhoon/leave-club): jwt 재발급 및 조건문 우선순위 변경 #315
  app/src/models/services/MyPage/MyPage.js
Labels: 기능 구현, API, DB

#325 [clubBoard] 동아리 별 활동 내역 및 공지 게시판 API
  app/src/models/services/AdminOption/AdminOptionStorage.js
  app/src/models/services/Board/Board.js
Labels: 서버, 기능 구현, API

#326 [Notification] 알림 API 수정
  app/src/models/services/Application/Application.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Notification/Notification.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/models/services/Schedule/Schedule.js
Labels: 서버, 기능 구현, API

#331 [Jest] 테스트를 위한 jest 설치와 설정
  app/jest.config.js
  app/package-lock.json
  app/package.json
  app/src/tests/admin-option.test.js
  app/src/tests/notification.test.js
  app/src/tests/review.test.js
Labels: 기획 및 설계

#332 [Jest] 동아리 관리, 알림, 후기 API에 대한 테스트 코드 작성
  app/package-lock.json
  app/package.json
  app/src/tests/admin-option.test.js
  app/src/tests/notification.test.js
  app/src/tests/review.test.js
Labels: 서버, 기능 구현, API

#334 Modify(jisu/admin-option): 동아리원들 조회할 때 개인 정보 데이터도 보내도록 수정
  app/src/models/services/AdminOption/AdminOptionStorage.js
Labels: 서버, 기능 구현, API

#337 [Notification] 알림 기능 추가
  app/src/models/services/Application/Application.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/tests/admin-option.test.js
Labels: 서버, 기능 구현, API

#341 [Jest] 동아리 관리, 후기, 알림 API에 대한 테스트 수정
  app/src/models/services/MyPage/MyPage.js
  app/src/tests/admin-option.test.js
  app/src/tests/notification.test.js
  app/src/tests/review.test.js
Labels: 서버, 기능 구현, API

#339 [OAuth 2.0] 네이버 아이디로 로그인 API
  app/app.js
  app/src/apis/naver/index.js
  app/src/apis/naver/naver.ctrl.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/middlewares/snsToken-auth.js
  app/src/models/services/Oauth/Oauth.js
  app/src/models/services/Student/Student.js
  app/src/models/services/Student/StudentStorage.js
Labels: 기능 구현, API, DB

#342 [OAuth 2.0] 네이버 아이디로 로그인 API
  app/src/models/services/Student/Student.js
Labels: 기능 구현, API, DB

#343 [Notification] 알림 기능 수정
  app/src/models/services/Application/Application.js
  app/src/models/services/Board/Board.js
  app/src/models/services/MyPage/MyPage.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/models/services/Schedule/Schedule.js
  app/src/tests/admin-option.test.js
  app/src/tests/review.test.js
Labels: 서버, 기능 구현, API

#344 Refactor(jisu/notification): 동아리 가입 승인 에러처리 수정
  app/src/models/services/Notification/Notification.js
Labels: 서버, 기획 및 설계, API

#346 [Admin option] 동아리 관리자 API 수정
  app/src/models/services/Application/ApplicationStorage.js
Labels: 서버, 기능 구현, API

#349 [OAuth 2.0] 네이버 아이디로 로그인 API
  app/src/apis/naver/naver.ctrl.js
  app/src/middlewares/snsToken-auth.js
  app/src/models/services/Oauth/Oauth.js
  app/src/models/services/Student/Student.js
  app/src/models/services/Student/StudentStorage.js
Labels: 기능 구현, API, DB

#347 [Emotion]: 좋아요 API 추가 및 익명기능
  app/.eslintrc.json
  app/app.js
  app/src/apis/emotions/emotion.ctrl.js
  app/src/apis/emotions/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Emotion/Emotion.js
  app/src/models/services/Emotion/EmotionStorage.js
Labels: 서버, 기능 구현, API

#350 [emotion] 동일 익명시 작성자 이름 안나오는 오류 수정 #335
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#352 [emotion]: 게시판 상세조회시 작성자 flag 추가 #335
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#353 [emotion]: 비로그인 회원시 게시글 상세조회 에러처리 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API

#351 [Notification] 동아리 탈퇴 api와 관리자 api 수정
  app/src/models/services/Application/ApplicationStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/MyPage/MyPage.js
Labels: 서버, 기능 구현, API

#354 [boards]: 게시판 상세조회시 대댓글 좋아요 수 안쌓이면 오류 수정
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#356 [OAuth 2.0] 네이버 아이디로 로그인 API
  app/src/models/services/Student/Student.js
  app/src/models/services/Student/StudentStorage.js
Labels: 기능 구현, API, DB

#358 [Login] 로그인 API
  app/src/apis/root/root.ctrl.js
  app/src/models/services/Student/Student.js
Labels: 기능 구현, API, DB

#359 [boards]: 게시글 상세조회시 작성자 익명일때 작성자 체크 수정
  app/src/models/services/Board/Board.js
Labels: 서버, 기능 구현, API

#357 [Jest] Jest를 이용한 test case 구축
  app/src/tests/login.test.js
  app/src/tests/signUp.test.js
Labels: 버그, 기능 구현

#348 [letter] 쪽지 API
  app/app.js
  app/src/apis/letter/index.js
  app/src/apis/letter/letter.ctrl.js
  app/src/models/services/Letter/Letter.js
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#360 [Search] 검색 API
  app/src/models/services/Board/BoardStorage.js
  app/src/tests/find-id.test.js
Labels: 기능 구현, API, DB

#361 [Notification] 알림 API 수정
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Emotion/Emotion.js
  app/src/models/services/Notification/Notification.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/tests/notification.test.js
Labels: 서버, 기능 구현, API

#363 [Profile]: 프로필 수정 시 네이버 유저 플래그 수정
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Student/StudentStorage.js
Labels: 서버, 기능 구현, API

#364 [Notification] 알림 API 수정과 알림 test 코드 분리
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Notification/NotificationStorage.js
  app/src/tests/board-notification.test.js
  app/src/tests/club-notification.test.js
  app/src/tests/notification.test.js
Labels: 서버, 기능 구현, API

#365 [Profile]: 프로필 수정 API 이메일, 전화번호 검증 추가
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Student/StudentStorage.js
Labels: 서버, 기능 구현, API

#366 [profile]: 프로필 수정 네이버 유저 검증 추가
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#367 [Application-form] 가입신청 답변 API
  app/src/models/services/Application/Application.js
  app/src/models/services/Student/StudentStorage.js
Labels: 서버, 기능 구현, API

#369 [api-key]: api-key 미들웨어 구현
  app/src/middlewares/api-auth.js
Labels: 서버, 기능 구현

#371 [boards]: boards API에 api-auth 미들웨어 추가
  app/src/apis/boards/index.js
Labels: 서버, 기능 구현, API

#372 [emotions]: emotions API에 api-auth 미들웨어 추가
  app/src/apis/emotions/index.js
Labels: 서버, 기능 구현, API

#374 [s3]: s3 API에 api-auth 미들웨어 추가
  app/src/apis/s3/index.js
Labels: 서버, 기능 구현, API

#375 Add(jisu/notification): apiAuth 미들웨어 적용
  app/src/apis/admin-option/index.js
  app/src/apis/notification/index.js
  app/src/apis/review/index.js
Labels: 서버, 기능 구현, API

#376 [Application-form] 동아리 가입 질문/답변 API
  app/src/apis/application/index.js
Labels: 서버, 기능 구현, API

#377 [Circle-home] 동아리 홈 API
  app/src/apis/circle-home/index.js
Labels: 서버, 기능 구현, API

#378 [Club-board] 동아리별 게시판 API
  app/src/apis/club-board/index.js
Labels: 서버, 기능 구현, API

#379 [Club-list] : 동아리 목록 조회 API
  app/src/apis/club/index.js
Labels: 서버, 기능 구현, API

#380 [Letter] 쪽지 API
  app/src/apis/letter/index.js
Labels: 서버, 기능 구현, API

#381 [My-page] 마이페이지 API
  app/src/apis/my-page/index.js
Labels: 서버, 기능 구현, API

#382 [Schedule] 동아리별 스케쥴 API
  app/src/apis/schedule/index.js
Labels: 서버, 기능 구현, API

#383 [Root] root 폴더 api-auth 미들웨어 추가
  app/src/apis/root/index.js
Labels: 서버, 기능 구현, API

#386 [profile]: 프로필 수정 이메일, 전화번호 검증 수정
  app/src/models/services/Profile/Profile.js
Labels: 서버, 기능 구현, API

#387 [Letter] 쪽지 API
  app/src/models/services/Letter/LetterStorage.js
Labels: 서버, 기능 구현, API

#388 [boards]: 게시판 상세조회 댓글부분 수정
  app/src/models/services/Board/Comment/Comment.js
Labels: 서버, 기능 구현, API
